### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by glalit15** [CANopenNode/CANopenSocket#26]
So I am new to CANopen and wanted to run the examples/basicDevice but when I enter make, I am getting an error

../../CANopenNode/socketCAN/CO_main_basic.c:28:30: fatal error: bits/getopt_core.h: No such file or directory

after this I tried to make in the CANopenNode respository and getting the same error as well. (I am running this on Ubuntu Mate)

P.S. I already have a hardware CAN Bus where I am reading the data from a sensor by ESP32 and sending it over CAN to a Linux system. Now I want to implement CANopen on this
![WhatsApp Image 2021-03-19 at 14 07 45](https://user-images.githubusercontent.com/56798607/111785261-a8135300-88bc-11eb-8e1f-9bd3f8b17b86.jpeg)

**Comment by CANopenNode** [comment]
Just remove unnecessary line with #include <bits/getopt_core.h>. (#include <unistd.h> should be enough.)
I fixed CANopenNode.

**Comment by spaceKelan** [comment]
I experienced the same problem with the CANopenDemo framework when trying to compile cocomm. I had to comment that line out and additionally add the CFLAG -std=gnu99 because with -std=c99 it would complain.
Error because <bits/getopt_core.h> not found
![image](https://github.com/CANopenNode/CANopenSocket/assets/51329415/6af8e635-3b12-463f-9eca-cd7d9798384e)
resolved by commenting line out as recommended by @CANopenNode 

Trying to ```make``` after commented library out
![image](https://github.com/CANopenNode/CANopenSocket/assets/51329415/f863bd8f-54a9-4f0a-a825-487f6d2c9eb5)

~~Added ```-std=c99``` flag to the makefile~~
![image](https://github.com/CANopenNode/CANopenSocket/assets/51329415/e2dd58bc-bb16-4d2e-970a-a20ff0bda5e7)

```make```
![image](https://github.com/CANopenNode/CANopenSocket/assets/51329415/26b7431e-3d52-4693-af2a-fc4e1d2faa84)

Instead of ~~```-std=c99```~~ flag, **```-std=gnu99```** flag is added to the makefile
![image](https://github.com/CANopenNode/CANopenSocket/assets/51329415/8cc75122-5790-45eb-a454-fe765a87fbb9)

```make```
![image](https://github.com/CANopenNode/CANopenSocket/assets/51329415/410fe278-81a6-4898-a6e8-7a204ba9dc30)

and the executable is build
![image](https://github.com/CANopenNode/CANopenSocket/assets/51329415/74d740a7-2e2c-4d85-9296-936ceb2c5848)

Hope this helps people on the same journey :)
